#!/bin/sh
sudo apt-get install libav-tools &&
pip3 install -r requirements.txt &&
sudo cp ./alarm /etc/init.d/ &&
sudo chmod 755 /etc/init.d/alarm &&
sudo update-rc.d /etc/init.d/alarm defaults &&
echo "You're ready to go!"
